name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        run: curl -s -X POST "${{ secrets.RAILWAY_FRONTEND_HOOK }}"

      - name: Deploy Backend
        run: curl -s -X POST "${{ secrets.RAILWAY_BACKEND_HOOK }}"
